version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/ts-eb-app

hooks:
  AfterInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ubuntu
