version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 730335183789.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building TypeScript project"
      - docker build -t demo-repository/docker-node-app .
  post_build:
    commands:
      - echo "Build completed"
      # - docker tag demo-repository/docker-node-app:latest 730335183789.dkr.ecr.us-east-1.amazonaws.com/demo-repository/docker-node-app:latest
      # - docker push 730335183789.dkr.ecr.us-east-1.amazonaws.com/demo-repository/docker-node-app:latest
      - printf '[{"name":"AppCluster","imageUri":"730335183789.dkr.ecr.us-east-1.amazonaws.com/demo-repository/docker-node-app:latest"}]' > imagedefinitions.json
      - echo "Push completed"
artifacts:
  # files: "**/*"
  files: "imagedefinitions.json"
